# Generated by Django 5.2.6 on 2025-10-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='tipo',
            field=models.CharField(choices=[('A', 'Antigo (sem zeros)'), ('B', 'Novo (com zeros)')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='patrimonio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='protocolo',
            unique_together={('tipo', 'patrimonio')},
        ),
    ]
