# Generated by Django 5.2.6 on 2025-10-21 17:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('estoque', '0003_protocolo_tipo_alter_protocolo_patrimonio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=120)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('data_solicitacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('CONCLUÍDA', 'Concluída'), ('NEGADA', 'Negada')], default='PENDENTE', max_length=20)),
                ('observacao_admin', models.TextField(blank=True, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.produto')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
