# Generated by Django 5.2.7 on 2025-10-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_solicitacaocompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='qrcode_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
